### ISSUE TITLE
[enhancement] MinecraftアカウントとDiscordアカウントの一対一の連携を強制する機能

### ISSUE THREAD

**Issue by wacch** [SIGMA-L/PlayerRoleChecker#4]
現在(Release4.2)の仕様では、一つのDiscordアカウントに複数のMinecraftアカウントを紐づけることができます。
この仕様はサブアカウントを保有するプレイヤーは複数のDiscordアカウントを用意する必要がなく、手間が省けるという利点があります。しかし、この仕様を逆手に取って一つのDiscordアカウントに複数人のMinecraftアカウントを紐づけることで、全員がDiscordサーバーに入らなくてもMinecraftサーバーに入ることができるようになり、荒らしが容易になったり、個人個人にDiscordサーバーへの参加を強制できなくなるという欠点もあります。
この欠点を補うために、configにてMinecraftアカウントとDiscordアカウントを一対一で連携することを強制するオプション及び機能の導入を希望します。
ご検討のほどよろしくお願いいたします。

**Comment by KoutaChan** [comment]
忙しいので１週間程度かかるかもしれませんが、4.21で実装します

**Comment by KoutaChan** [comment]
4.21で実装しました

config.yml 等を再生成して設定してください 

`Discord.limits.canRegisterUnlimitedAccount` をfalseにして 
`Discord.limits.maxAccountPerDiscord`  で最大可能登録数を指定してください

**Comment by wacch** [comment]
実装感謝いたします！
早速利用させていただきます
